version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: elom
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
